### ISSUE TITLE
StationWare Oriented Tips

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [StationWare/stationware#110]
I think most challenges are self-explanatory but some plain-assed tips would be nice

**Comment by EmoGarbage404** [comment]
do tips ever display? i don't think rounds or the lobby are actually long enough for them to ever appear.

**Comment by Just-a-Unity-Dev** [comment]
> do tips ever display? i don't think rounds or the lobby are actually long enough for them to ever appear.

i don't even think our repo even has tips considering its latest commit

**Comment by Just-a-Unity-Dev** [comment]
nevermind it does infact have tips
