### ISSUE TITLE
Lobby music

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [StationWare/stationware#140]
Vengabus, Tally Hall, [This Track](https://youtu.be/2ZWRasF9sPg), Filk Songs, etc etc

**Comment by EmoGarbage404** [comment]
Uhhhh are we just gonna say "fuck copyright"

**Comment by Just-a-Unity-Dev** [comment]
I'm fairly sure most filk songs are public domain however I'm not sure about the former

**Comment by EmoGarbage404** [comment]
Can we have a secret submodule with all of the copyright offendint music?

**Comment by Just-a-Unity-Dev** [comment]
I have no idea how to make that work with SS14.Watchdog

**Comment by EmoGarbage404** [comment]
Also, we might have to edit the songs considering that the total lobby length is only 30 seconds.

**Comment by Just-a-Unity-Dev** [comment]
> Can we have a secret submodule with all of the copyright offending music?

Probably?
