### ISSUE TITLE
sometimes challenges don't end

### ISSUE THREAD

**Issue by EmoGarbage404** [StationWare/stationware#157]
## Description

really weird and random. no clue what that is.

**Comment by Just-a-Unity-Dev** [comment]
i can repro on the cm and xeno queen ones, but aside from that it's completely random

**Comment by EmoGarbage404** [comment]
What are the steps?

**Comment by Just-a-Unity-Dev** [comment]
1. run the xeno event
2. 30% chance it just refuses to work
