### ISSUE TITLE
equip clothing modifier sometimes fails and spawns too much clothing

### ISSUE THREAD

**Issue by EmoGarbage404** [StationWare/stationware#161]
## Description

probably some logic shit
**Reproduction**

**Screenshots**

**Additional context**

**Comment by Just-a-Unity-Dev** [comment]
this is probably related to fuckers bugging the game and having the clothing after the round has ended

**Comment by EmoGarbage404** [comment]
this was caused by players ghosting in the 1 second between the announcement and the challenge starting. it would cause the InventorySystem GetSlots call to throw an exception and likely throw all the wacky behavior mentioned above.
