### ISSUE TITLE
Quicktime Event Scoring System

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [StationWare/stationware#36]
Essentially, if you pass the quicktime event you get 1 point.

If you are in the top 3, you get additional points. (1 gets 4, 2 gets 3, 3 gets 2)

If you lose, you get 0 points

**Comment by EmoGarbage404** [comment]
so, a thing to consider:
if we have a mix of traditional pass/fail events and quicktime events, how do we ensure scoring isn't a mess? Some events, everyone will "win" equally (such as survival) and thus they should receive the same amount of points. Should everyone get 3? Or only 1? Any way you cut it, you end up with a weird issue between all of them.

**Comment by Just-a-Unity-Dev** [comment]
I feel this is overcomplicating how stationware should work therefore I am going to close it
